
export const PROFILE__LOAD_PROFILES_SUCCESS = 'PROFILE__LOAD_PROFILES_SUCCESS';
export const PROFILE__UPDATE_PROFILES_SUCCESS = 'PROFILE__UPDATE_PROFILES_SUCCESS';
export const PROFILE__CREATE_PROFILES_SUCCESS = 'PROFILE__CREATE_PROFILES_SUCCESS';
