name: Static Demo Site

# Controls when the action will run. Triggers the workflow on push
on:
  push:
    branches:
      - 'scale-7'
  pull_request:
    branches:
      - 'scale-7' 
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: tibor19/static-website-deploy@v1
        with:
          enabled-static-website: 'true'
          blob-container-name: '$web'
          folder: '.'
          connection-string: ${{ secrets.CONNECTION_STRING }}
          remove-existing-files: 'true'
